### ISSUE TITLE
customizing fields in the booking form (add address fields)

### ISSUE THREAD

**Issue by fragmichdoch** [timekit-io/booking-js#10]
i want to define which input fields the booking form should contain. and which of them should be mandatory.

e.g. we would need to enable the booking user to set an address where the appointment should take place.

**Comment by laander** [comment]
@fragmichdoch 

Would you mind giving this PR https://github.com/timekit-io/booking-js/pull/33 a look and tell me if it solves your problem? Thanks

**Comment by laander** [comment]
Released in [v1.4.0](https://github.com/timekit-io/booking-js/releases/tag/v1.4.0)
