### ISSUE TITLE
Multiple event slots - expose method showBookingPage() ?

### ISSUE THREAD

**Issue by mtt87** [timekit-io/booking-js#106]
I'm trying to implement a multiple slot booking.
![screen shot 2016-05-27 at 17 02 45](https://cloud.githubusercontent.com/assets/2150927/15613814/593d8294-242d-11e6-8505-55622e3efc07.png)

I can use the `eventClick` handle of fullCalendar to select multiple event slots

``` js
eventClick: function (calEvent, jsEvent, view) {
  var $el = $(this);
  // check if it's not already selected otherwise unselect it
  if (selectedRange[calEvent._id]) {
    delete selectedRange[calEvent._id];
    $el.removeClass('selected');
  } else {
    selectedRange[calEvent._id] = {};
    $el.addClass('selected');
  }
}
...
// $('.book-button').click(function(){
//   showBookingPage
// });
```

But then I'm unable to call showBookingPage() since the method is not exposed.
https://github.com/timekit-io/booking-js/blob/a4e443da03b9e48b45b296e31724497acd1af795/src/main.js#L293-L348

Any suggestion?
Should I fork the project and expose this method by myself or is it something that can be useful for other people?

Thanks! 😄

**Comment by laander** [comment]
@mtt87 That's a quite interesting feature! :)

We actually had a quite a few requests for something related to this. In general, I see 2 different ways to achieve this:

1) Visitors are able to select multiple slots in the same view, just like you're proposing. 
  One question arise though: what should happen when you click (currently non-existing) "Continue" button; would a single form be shown that, when confirmed, would result in multiple bookings? Should these bookings be linked somehow? Or would 1 booking with multiple timeslots be preferred?

2) The visitor can select timeslot duration from a dropdown, e.g. 1 hour, 2 hours, 3 hours. Availability would then be fetched and we could keep the same views and booking process as of right now. This would only work for durations that are in continuation, so if visitors were to pick one timeslot on Monday and another on a Thursday, they would still have to go through the booking two times.

Solution number 2 is a lot more simple from a technical point of view, but might not suffice your use-case.

What's your thoughts?

NB; I'd love to develop this in the open and would gladly help you out, as I'm sure it could be beneficial for others too.

**Comment by mtt87** [comment]
First of all method exposed:
https://github.com/techhubdotcom/booking-js/commit/b72afd3f0e30758559c0ea3723e1da4ae7821491

I went for 1) as my use case is simpler:
- You can only make 1 booking
- You have to select consecutive time slots, you can't book at 10:30 and then at 14:30, they need to be 2 separate bookings  
For these reason I'm writing some code to prevent people from selecting slots that are not consecutive
```js
eventClick: function(calEvent, jsEvent, view) {
    var $el = $(this);

    var id = parseInt(calEvent._id.replace(/^\D+/g, ''));
    var consecutive = false;

    //  check if it's adjacent to a previous selection, if selectedRange is not empty
    if (self.selectedRange.length > 1) {
        self.selectedRange.forEach(function(e) {
            var idToCheck = parseInt(e._id.replace(/^\D+/g, ''));
            if (idToCheck - id === -1 || idToCheck - id === 1) {
                consecutive = true;
            }
        });
    }

    if (consecutive || self.selectedRange.length < 2) {
        // check if it's not already selected otherwise unselect it
        var selected = _.findIndex(self.selectedRange, ['_id', calEvent._id]);
        // TODO check index should be first or last item (to avoid removing in the middle)
        if (selected > -1 && (selected === 0 || selected === self.selectedRange.length - 1)) {
            $el.removeClass('selected');
            self.selectedRange.splice(selected, 1);
            console.log(self.selectedRange.length);
        } else {
            self.selectedRange.push(calEvent);
            $el.addClass('selected');
        }
    } else {
        // TODO
        window.alert('not consecutive');
    }
    // keep it sorted
    self.selectedRange = _.sortBy(self.selectedRange, ['_id']);
    self.update();
}
```
![screen shot 2016-06-01 at 19 04 21](https://cloud.githubusercontent.com/assets/2150927/15720432/4bc0bf84-282c-11e6-9327-d260196172a9.png)

Then I call `showBookingPage(event)` and I pass this event
```js
{
  "start": // start_date
  "end": // end_date
}
```
I'm thinking about this flow:
- Booking-js widget is creating the booking as `confirm_decline` - tentative
- When the callback `createBookingSuccessful` is triggered I get the start/end and I calculate the duration and I can send the user to the payment step
```js
createBookingSuccessful: function (response) {
  $('.bookingjs-form-success-message').css('position', 'relative');
  var start = moment(response.data.attributes.event.start);
  var end = moment(response.data.attributes.event.end);
  var diff = end.diff(start, 'minutes');
  // TODO send user to payment
}
```
- I will prompt the user to pay and if the payment is successful I will call the timekit API to confirm the booking


Does it makes sense?

**Comment by laander** [comment]
Hey @mtt87!

Have you made any progress on his?

Although i like your approach, I feel it's somewhat hacky and will take some new UI elements (a "continue" button) to get to work properly. The main advantage though is that it enables more granular selection because FindTime only returns timeslots in sequential blocks.

I'm still considering going with option 2) as it re-uses FindTime and can be made by a simple "select duration" step before showing the calendar. If that wouldn't work for you though, I'm keen on continuing down your path - let me know :)

**Comment by mtt87** [comment]
Hey @laander I've basically built it 😄 
![screen shot 2016-06-22 at 15 46 18](https://cloud.githubusercontent.com/assets/2150927/16271088/81761178-3890-11e6-81dc-70b64b64c7b6.png)


Have a look (test url):
http://th-bookings.s3-website-eu-west-1.amazonaws.com/#book/?room_id=4eDwdJdB4Qg6g8WCcwucAs

Quick question how can I add more fields that will be shown in the confirmation page?
![screen shot 2016-06-22 at 15 47 15](https://cloud.githubusercontent.com/assets/2150927/16271126/a5445862-3890-11e6-9d33-d4b4d25bf29f.png)

If I add a field here it doesn't show up
```js
bookingFields: {
  ...
  my_custom_field: {
    placeholder: 'Hello world',
    prefilled: false,
    locked: false
  },
```

**Comment by laander** [comment]
Good stuff man! :)

That's actually really functional, great job.

I've played around with another approach where you select/click-and-drag timeranges instead, see a small demo here: https://www.dropbox.com/sc/xigsbwssznvoz3a/AADOnYbSdbu7J15ZpgpNIVFha
It still need some work on the backend to be workable (FindTime should basicially "invert" the resulting availability), but it's MVP.

And there's still option 2 to try. Still not sure what the best approach is, but if you feel like, please make a PR with your changes and I'll see if I can make it a native feature :)

Regarding the booking fields, custom fields are not supported right now unfortunately. It's on the roadmap though - what kind of fields are you looking to use?

**Comment by mtt87** [comment]
In my use case I was looking to add `duration` and `amount` so people can confirm they are happy with that.

I'm happy to create a PR but I have the feeling this is something mostly related to our use case
