### ISSUE TITLE
how to manage booking between 9 to 5 (office timing) only??

### ISSUE THREAD

**Issue by taksunil** [timekit-io/booking-js#111]

**Comment by laander** [comment]
Hi @taksunil,

You can use the FindTime filters to restrict the availability range, in particular `specific_time` one. See the docs: http://developers.timekit.io/docs/find-time-filters

Here's how you add them to your booking.js configuration: https://github.com/timekit-io/booking-js#--timekitfindtime

**Comment by taksunil** [comment]
Thanks laander :)
