### ISSUE TITLE
Single Day View on Mobile is Stuck on Today's View

### ISSUE THREAD

**Issue by korymcandrew** [timekit-io/booking-js#117]
When using the widget on mobile device resolutions it shrinks down to the single day view, which it should, however the two arrows for going forward and backwards are disabled, effectively making you stuck on the current day.

![timekit](https://cloud.githubusercontent.com/assets/9453076/19659515/48692c82-99fa-11e6-9605-dafb35d02388.png)

**Comment by korymcandrew** [comment]
A quick note: you can fix this by firing the following jquery after the page has loaded:
$(".is-small").removeClass("is-small");

I'm not sure if they will have an effect on anything else, but it at least allowed us to solve the issue until we hear back from the Timekit team.

**Comment by laander** [comment]
@korymcandrew Thanks for reporting!! You are right, this only happens if a displayName is shown and with no avatar chosen. I've made a PR that fixes this and expect to release it on monday (#119)

**Comment by korymcandrew** [comment]
Great, thanks for the quick turnaround!

**Comment by laander** [comment]
@korymcandrew Just released it now. Happy fridays 🎉

**Comment by korymcandrew** [comment]
I have confirmed the new build fixes the issue.  Thanks again!
