### ISSUE TITLE
findtime request with multiple calendars looks at  single calendar

### ISSUE THREAD

**Issue by korymcandrew** [timekit-io/booking-js#122]
It appears like the calendarId is not being taken into account when the findtime request occurs.  We have two calendars associated to the same google account.  When we display the bookingjs widget for either calendar, the same slots are returned.  For example, we book an event on calendar 1.  We then open calendar 2.  The slot that was booked in calendar 1 appears as booked on calendar 2.

Examining the POST request for findtime, we see that Timekit-App and the email address associated to the google account, however we cannot see the calendarId being used anywhere.

**Comment by vistik** [comment]
hi @korymcandrew Could you write on our intercom chat on timekit.io? just reference this issue
