### ISSUE TITLE
Calendar Sync Issue

### ISSUE THREAD

**Issue by ArtursO** [timekit-io/booking-js#126]
Hey @laander we have a booking widget under the account rahul@anant.us and the calendar sync isn't occurring automatically even though under the "Connection Status" section found in the Sync Tab it states "Your account is being automatically synced". I went in today to check and the last sync had occurred a few months ago, I then manually synced today. Do you have any ideas why this might be occurring?

**Comment by laander** [comment]
Hi @ArtursO please write us a message through Intercom live chat on https://admin.timekit.io , then I'll help you from there :)
