### ISSUE TITLE
fullCalendar language option doesn't work

### ISSUE THREAD

**Issue by vdaniuk** [timekit-io/booking-js#15]
fullCalendar language option is documented here http://fullcalendar.io/docs/text/lang/ but I couldn't get it to work with booking-js. 

I've tried both basic booking-js option
`
{ 
...
fullCalendar: { lang: "de" },
...
}
`

and explicit widget init

`
var widget = new TimekitBooking();
widget.init(config);
widget.fullCalendar({
            lang: "de"
          });
`

Is it possible to use different languages with booking-js at this moment? Thanks.

**Comment by laander** [comment]
@vdaniuk 

I'm working on a PR that adds proper localization support, should be up on Monday :+1: The only gotcha is that you need to load the fullcalendar language yourself, as adding all languages by default would increase the library size by +100kb.

Next step is localization support for all text strings in the booking form.

**Comment by laander** [comment]
@vdaniuk 

PR ready: #17 - is that sufficient enough for you at the moment?

**Comment by laander** [comment]
Fix released in [v1.2.2](https://github.com/timekit-io/booking-js/releases/tag/v1.2.2), closing issue

**Comment by vdaniuk** [comment]
@laander Thanks for a fast update! Lang option seems to be working fine.
