### ISSUE TITLE
Phone Numbers

### ISSUE THREAD

**Issue by Amakaruk** [timekit-io/booking-js#16]
Can this be customized to collect phone numbers when someone reserves a slot on your calendar?

**Comment by laander** [comment]
Hi @Amakaruk 

Yeah, I don't see why not. Currently, I'd recommend doing it through the comment/description field, as that is saved on the event in Google calendar. I'm also looking into support for custom fields (see #10) so you can pick them yourself. What's your thoughts?

**Comment by kevingmcelroy** [comment]
Yes this would be great - Id love to see a phone number and skype field available!

**Comment by laander** [comment]
@Amakaruk @kevingmcelroy Could you take a look at the following PR and tell me if that's sufficient for you? https://github.com/timekit-io/booking-js/pull/33
Thx!

**Comment by Amakaruk** [comment]
That's great - what about Stripe payment integration, eh? But nice work on
the new fields - that's helpful.

**Comment by laander** [comment]
@Amakaruk I've got a separate issue on that https://github.com/timekit-io/booking-js/issues/20 - throw a vote there and I'll take a look at it :)

**Comment by laander** [comment]
Released in [v1.4.0](https://github.com/timekit-io/booking-js/releases/tag/v1.4.0]
