### ISSUE TITLE
How can I use the widget to update a booking event instead of creating an event?

### ISSUE THREAD

**Issue by biplovdahal** [timekit-io/booking-js#169]
Right now; when I render the calendar it always seems to be calling .createBooking; instead I want to updateBooking using the same flow; I'd just need to be able to pass in the event ID; and update the booking start and end_time based on new event start and end time; but same event ID. 

I also looked into using callbacks; no idea how I'd be able to do that.
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js" defer></script> <script src="https://cdn.timekit.io/booking-js/v1/booking.min.js" defer></script> 
                
        
                        <script>
                            

                            window.timekitBookingConfig = { 
                                widgetId: '', 
                                app:'',
                                email:'',
                                apiToken:'',
                                calendar:'',
                                bookingGraph:'confirm-decline',
                                availabilityView:'agendaWeek',
                          };
                     </script>

**Comment by Trolzie** [comment]
Hi there @biplovdahal 
Unfortunately the calendar isnt built to be able to update events. I suggest you do that using our API instead. you can read more about that here: http://developers.timekit.io/docs/bookings

**Comment by biplovdahal** [comment]
So there is no way for me to use the calendar widget and update an booking; using the API? There is no way to void .createBooking(args) method and throw .updateBooking(args) instead?

**Comment by biplovdahal** [comment]
Perhaps around the callback?

**Comment by biplovdahal** [comment]
Found a way around to this; just to use the widget and to get the calendar data; what I did was I simply threw bookingGraph:  confirm-decline; which threw error upon creating a booking and did not create a booking at all; then I used call back like this: then I'd pass data I obtained from `showBookingPage` to my backend and make a PUT request to update the time in timekit. 

```
 window.timekitBookingConfig = { 
bookingGraph:'confirm-decline',
callbacks:{
     showBookingPage:     function(slot){
      slot.start._i, slot.end._i
}
}
}
```

**Comment by Trolzie** [comment]
@biplovdahal well if it works, power to ya. But If you are just using the widget for getting booking data, there are easier ways around this. But you are showing the widget right?

**Comment by biplovdahal** [comment]
I am showing the widget; correct. Looks like there is a bug; the calendar data doesn't seem to be properly syncing with API data specially for getting availability times; when a certain is not booked anymore it still doesn't show that slot as bookable.

**Comment by Trolzie** [comment]
@biplovdahal just make thins clear, then it isnt possible to update start/end in an existing bookings. This is a conscious decision on our part in the state machine.
