### ISSUE TITLE
Fetch availability not working properly

### ISSUE THREAD

**Issue by DhavalRadhanpara** [timekit-io/booking-js#188]
we are having problem with "fetchAvailability". params ar eas follows
 `"{\"mode\":\"mutual\",\"resources\":[\"resource id\"],\"length\":\"15` 
   ` minutes\",\"ignore_all_day_events\":false,\"constraints\":[{\"allow_day_and_time\":`
    `{\"day\":\"monday\",\"start\":10,\"end\":20}},{\"allow_day_and_time\":`
   ` {\"day\":\"tuesday\",\"start\":10,\"end\":20}},{\"allow_day_and_time\":`
    `{\"day\":\"wednesday\",\"start\":10,\"end\":20}},{\"allow_day_and_time\":`
    `{\"day\":\"thursday\",\"start\":10,\"end\":20}},{\"allow_day_and_time\":`
    `{\"day\":\"friday\",\"start\":10,\"end\":20}}],\"output_timezone\":\"US/Eastern\"}"`.  Though we have set allow day and time it is giving slots for whole day. we make resource from application and resource does not set availability from timekit dashboard (it is set from our app).

**Comment by laander** [comment]
Hi @DhavalRadhanpara , if you're still having problems, please contact our support at https://www.timekit.io/contact-us - thanks!
