### ISSUE TITLE
Using HTTPS 

### ISSUE THREAD

**Issue by BoweFrankema** [timekit-io/booking-js#19]
Is there any way to use HTTPS via your CDN? I'd like to use the widget but sadly get the following error on our site:

````
https://cdn.timekit.io/booking-js/v1/booking.min.js Failed to load resource: net::ERR_INSECURE_RESPONSE
````

:crying_cat_face:

**Comment by laander** [comment]
@BoweFrankema 

CloudFront requires some configuration to get SSL to work on custom domains (https://aws.amazon.com/cloudfront/custom-ssl-domains/). I'm on it though, hope to get it flying within the next couple of days, will report back when it's up and stable!

**Comment by slateid** [comment]
Yes I would also like to be able to use this on a secure site. Thanks for the amazing widget.

**Comment by monfresh** [comment]
I just came across this, and was interested in using it as it looks really neat, but unfortunately won't be able to until HTTPS is supported. Any idea when we can expect this to happen? Thanks!

**Comment by monfresh** [comment]
Also, let me know if you need help setting up SSL certificates on AWS. Although I haven't used custom domains for Cloudfront, I have experience with setting up HTTPS for a static S3 site that uses Cloudfront.

**Comment by pfista** [comment]
Might be too late, but https://letsencrypt.org/ just opened up their public beta December 3rd.

**Comment by laander** [comment]
@BoweFrankema @slateid @monfresh @pfista 

Thanks all for following up. The short-term solution is to use our Cloudfront URL to serve HTTPS traffic, as Amazon already provides a certificate to this. Here's the full URL:
https://dbhpllgef527b.cloudfront.net/booking-js/v1/booking.min.js

(it resolves to the same resource as http://cdn.timekit.io/booking-js/v1/booking.min.js, so library updates will deployed and cache-busted on both addresses).

@monfresh Appreciate the offer, please write me on la@timekit.io and I'll explain you the problem :+1: 
@pfista We already have a certificate and I don't think Let's Encrypt supports Cloudfront (I can't see how), but thanks for the suggestion though
