### ISSUE TITLE
jQuery 3.5.1 incompatibility

### ISSUE THREAD

**Issue by boardfish** [timekit-io/booking-js#213]
Symptoms seem similar to #5348 in that `fc-bg` `div`s keep nesting inside one another, but I've verified that I'm using the fixed version of FullCalendar (3.10.2) and jQuery 3.5.1.

**Comment by aliasaria** [comment]
We recently upgraded to jQuery 3.6.0. Can you let us know if the issue is resolved?

**Comment by boardfish** [comment]
Upgraded the library the other day and I can confirm that the issue's resolved.
