### ISSUE TITLE
REST API?

### ISSUE THREAD

**Issue by bradvogel** [timekit-io/booking-js#22]
Do you offer a REST API so we can generate our own "booking widget" using your data?

**Comment by laander** [comment]
Hey @bradvogel - we absolutely do! The widget is actually built on top of the Timekit API, which I think is what you're looking for. 

Check out the docs here http://developers.timekit.io and if you're coding in javascript, we have a JS SDK too https://github.com/timekit-io/js-sdk (which is what the widget is using)

Let me know if there's any implementation details I can help with
