### ISSUE TITLE
Missing LICENSE or COPYING file

### ISSUE THREAD

**Issue by omouse** [timekit-io/booking-js#32]
I was unsure of what license the code was under so I didn't want to risk looking at it at all.

Please include a LICENSE that indicates if this is a GPL v3, LGPL, Apache license or some other license.

Thanks

**Comment by laander** [comment]
That is definitely missing, thanks for pointing that out :+1: 

Added it now (MIT): https://github.com/timekit-io/booking-js/blob/master/LICENSE.md
