### ISSUE TITLE
Handling deleted events?

### ISSUE THREAD

**Issue by alialkhatib** [timekit-io/booking-js#48]
Maybe this is an issue on Google Calendar's side, but I'm noticing that when I create an event in Google Calendar (thus blocking booking.js from offering slots overlapping with that event), whatever mechanism that prevents booking.js from offering those slots persists even after I **delete** the event on Google Calendar.

The process for replicating this is:
1. using Google Calendar as the backend, load the booking widget to see availability for a given timeframe (e.g. verify that you see bookable slots from 9am-5pm tomorrow).
2. create an event in Google Calendar conflicting with part of that timeframe (e.g. make an event for tomorrow from 10am-11am).
3. reload the booking widget, verifying that any booking slots that conflict (in the previous example, overlapping with the 10am-11am appointment) are no longer available.
4. delete the event from Google Calendar.
5. reload the booking widget, verifying that the absent slots have *not* reappeared.

I considered that maybe this was a problem with latency (i.e. Google Calendar is just slow to report that the block has been freed up), but I never saw the timeframe corresponding to the deleted event get freed back up. I'm also reluctant to come to that conclusion since booking.js reflected the unavailability of that timeframe quickly (in other words, it updated very quickly after I created the event in Google Calendar).

Has anyone else encountered this? Is there a good workaround or alternatively some way to prevent it from happening?

If this has all been confusing, I'd be happy to try and walk through the problem more verbosely, even screen-capturing the above steps to illustrate it - I'd just need some time.

**Comment by alialkhatib** [comment]
Not sure what the deal is, but I can't replicate this issue when I go through the demo/embed code process on the site, so I'm figuring that this is a problem with my setup. Sorry about that!

**Comment by laander** [comment]
@alialkhatib 

Thanks for reaching out. It's not totally clear right now, but the Google sync (from Google to Timekit) runs twice daily. This means that changes your doing in Google (adding new events) is first taken into account in the availability check when we've synced with your account, which can take up to 12 hours. If you want to trigger a sync manually, you can do a booking (each "create event" action from the widget triggers a sync subsequently) or call our API directly (http://developers.timekit.io/docs/accountssync).

We're looking into implementing "sync watches", where we subscribe to Google webhooks that trigger syncs instantly when changes occur, but it's still on the drawing board.

Hope this explains your frustrations (and sorry for the lack of communication on that parts) :+1:

**Comment by alialkhatib** [comment]
No, that makes sense - thanks for the follow-up and clarification! I think in the meantime we'll just rely on that (up to) 12-hour lag. I'm not anticipating lots of scrambling among users in my case, but I'll think about implementing direct API calls if the need arises.

Thanks again!

**Comment by laander** [comment]
Sounds good :+1:
