### ISSUE TITLE
Suggestion: Quick booking, without email confirmation

### ISSUE THREAD

**Issue by lenamtl** [timekit-io/booking-js#49]
Hi,

I don't know if it is already possible...
I need a quick booking without sending email confirmation to the client
No email field mandatory

Thanks

**Comment by laander** [comment]
Hi @lenamtl 
You can specify not to send invites/confirmation to the visitor booking the timeslot through the config:
```
timekitCreateEvent: {
  invite: false
}
```
The e-mail field is always required though. What would expect happen without an email set, in Google calendar? No participant added?

**Comment by lenamtl** [comment]
Good to know, thanks.

About email I mean the email field into participant form ..
