### ISSUE TITLE
"Book It" button isn't easily clickable when showCredits is true

### ISSUE THREAD

**Issue by monfresh** [timekit-io/booking-js#50]
I finally found the time to test the widget, and I ran into an issue where the "Book It" button seemed like it wasn't working at all. Then, I noticed that the only way to click it while the credits were present was to very slowly slide the cursor over the top of the button. I tried this in the latest versions of both Chrome and Safari on OS 10.10.5 (Yosemite). In Safari, the credits actually overlap the Book It button, but in Chrome, there is a little space in between them.

The solution to make the button clickable at all times, like it should be, was to disable the credits, which is unfortunate, because I'd like to show my support.

**Comment by monfresh** [comment]
If you inspect the credits link in the browser developer tools, you'll notice that the anchor tag takes up a large area that overlaps the Book It button, which is causing this issue.

Chrome: http://cl.ly/image/1S1I27281f0c
Safari: http://cl.ly/image/1u121X0c0v44

**Comment by monfresh** [comment]
I'm not a CSS expert, but I played around with the `bottom` and `padding` attributes of the `bookingjs-poweredby` class (in the div right above the anchor tag) and was able to move it down enough to make the button clickable in Chrome, but the same settings made the credits go down too low in Safari.

**Comment by laander** [comment]
@monfresh Thanks for reporting this. My best bet is that there's some global CSS styling on your page that in some way forces the `bookingjs-timekiticon` SVG move up to it's own line. 

On the demo page (http://booking.timekit.io) this doesn't happen, see screenshot:
<img width="386" alt="screen shot 2015-12-09 at 14 59 31" src="https://cloud.githubusercontent.com/assets/222419/11687223/a8d6ba7e-9e85-11e5-8a10-68d7112e0a77.png">

Could you grant me access to the site you're embedding it on? Or check the CSS rules that gets applied to: `<svg class="bookingjs-timekiticon" viewBox="0 0 495 594" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns"></svg` ?
