### ISSUE TITLE
Future cannot be more than 1 month?

### ISSUE THREAD

**Issue by alvinwoon** [timekit-io/booking-js#55]
Is there a plan to extend this? For event planning services (wedding and etc), a further view of timeslots in the future is needed. Perhaps extend it to 6 months?

**Comment by laander** [comment]
@alvinwoon Yes, we're currently working on improving performance for big result sets and I'll make an update here when we extend it :+1:

**Comment by alvinwoon** [comment]
awesome. looking forward to it! Thanks.

**Comment by laander** [comment]
@alvinwoon We've increased the max future to 6 months now :+1: Please give it a shot and let me know if you experience any severe performance degradation.

**Comment by alvinwoon** [comment]
Thanks!
