### ISSUE TITLE
More expressive success text

### ISSUE THREAD

**Issue by laander** [timekit-io/booking-js#6]
The success message after booking complete could be more clear and expressive, preferably with a message

**Comment by fragmichdoch** [comment]
![bildschirmfoto 2015-11-18 um 23 04 10](https://cloud.githubusercontent.com/assets/15915066/11255840/c5bc92b4-8e48-11e5-8c8a-1b261566d6ad.png)

this might help :)

**Comment by laander** [comment]
Thanks for the quick mockup! Here's my first take on it:

<img width="739" alt="screen shot 2015-11-19 at 10 57 14 am" src="https://cloud.githubusercontent.com/assets/222419/11267581/68c64aaa-8eac-11e5-902c-b6b02cae20a1.png">

**Comment by fragmichdoch** [comment]
looks fine! two things
- you still don't tell the user what to do next. a reasonable number might think that the slot has been finally booked and will forget to confirm
- as the user has typed in his/her email address only once, it might be better to show the email address, again

..just my two cents

**Comment by laander** [comment]
Fair points, updated again: 
<img width="383" alt="screen shot 2015-11-19 at 4 15 19 pm" src="https://cloud.githubusercontent.com/assets/222419/11274386/d420fd64-8ed8-11e5-8f6b-f700fc6ee63d.png">

**Comment by fragmichdoch** [comment]
release! ;)

..you will probably gain some experience while you A/B test the wording. If you ask me, I would always prefer a wording that tells **exactly** what to do next and expresses urgency. e.g "Please do now check your mailbox and accept the invitation to confirm the booking."..your call :)

**Comment by laander** [comment]
While i agree with what you're saying, it's a little complicated in this case because
1) We're short on space and I want to keep the wording as short possible (while still conveying the right message)
2) If the recipient has a Google account, you can actually skip the inbox skip totally - the invitation can be accepted directly from Google calendar. Therefore, I'd like to signal that in a more generic manner

I'll release this tonight and we'll see what the feedback says :)

**Comment by laander** [comment]
Released in v1.2.0, closing..
