### ISSUE TITLE
Today, Back, and Forth Buttons on Mobile View Do Not Work 

### ISSUE THREAD

**Issue by lawrence89** [timekit-io/booking-js#65]
For some reason whenever I view the calendar on my mobile device, I cannot seem to click on the previous/next date buttons nor can I click the today button to see today's availabilities. However if I visit http://booking.timekit.io/ on my mobile device, those buttons are working fine. Anyone have any idea why its not working on my webpage?

**Comment by lawrence89** [comment]
After playing around css for a bit, I realized the issue was the bookjs-displayname div was laid over the buttons making it difficult to select the buttons. I just used cssed to make the width of the container smaller so the buttons are no longer blocked.

**Comment by laander** [comment]
@lawrence89 Sorry for the late reply, but glad to hear you got it sorted out! Yeah, the div was overlapping the buttons a bit (about 30%) so some clicks/taps didn't make it through. I have a PR ready and will be fixing that in the next release :+1:
