### ISSUE TITLE
Uncaught ReferenceError: data is not defined

### ISSUE THREAD

**Issue by haghadi** [timekit-io/booking-js#68]
I'm getting this error on line:
 start:        data.start,      // Inserted from the chosen timeslot
 
Here is my code
<script type="text/javascript">
    window.timekitBookingConfig = {
      name: 'Dr. Nizar | Sharq Dental',
      email: 'haghadi@gmail.com',
      apiToken: '',
      calendar: '',
      avatar: '', 
      showCredits: true, // Display a "Powered by Timekit" attribution footer (thanks!)
      goToFirstEvent: true, // Display and scroll to the first upcoming event in the calendar (to avoid showing a blank calendar)

      localization: {
        showTimezoneHelper:     false, // Should the timezone difference helper (bottom) be shown?
        timeDateFormat:         '12h-mdy-sun' // For EU-style formatting, use '24h-dmy-mon' (see below)
      },

      bookingFields: {
        phone : {
          enabled: true,
          required: true
        }
      },

      timekitFindTime: {
        filters: {
          and: [
            {
              business_hours: { }
            },
            {
              exclude_weekend: { }
            }
          ],
          or: [
            {
              specific_time: {
                start: '00',
                end: '12'
              }
            },
            {
              specific_time: {
                start: '13',
                end: '24'
              }
            }
          ]
        }
      },

      timekitCreateEvent: {
        where: 'Sharq Dental Center', // Default, you may want to customize this to a specific location, TBD or whatever fits
        invite:       true,            // Default, makes sure that participants (the visitor) is sent a Google invite
        my_rsvp:      'accepted',   // Default, makes sure that the host also will be able to RSVP to the created event
        start:        data.start,      // Inserted from the chosen timeslot
        end:          data.end,        // Inserted from the chosen timeslot
        what:         config.name + ' x '+ data.name, // Inserted based on the host and visitors names (you can replace it with a static string)
        calendar_id:  config.calendar, // Inserted from the "calendar" setting in the general config
        participants: [config.email, data.email], // Inserted based on host and visitors ()
        description:  data.comment || '' // Inserted based on the visitor's supplied comment
      }
    }
  </script>

**Comment by laander** [comment]
Could you try and post your code again? It seems it got stripped out from your message.

It look like you're trying to configure the `timekitCreateEvent` with a custom start date. Be aware that the `start: data.start` from https://github.com/timekit-io/booking-js#timekit-create-event is merely an example of what is set dynamically inside Booking.js - if you want to override it, you'll have to set it to a timestamp string value. If in doubt, just exclude it (I don't think you want to override it)

**Comment by haghadi** [comment]
Hey Lasse,

Thanks for the reply. Yes, I've excluded it. It's working now. Thanks!

On Mon, Jan 25, 2016 at 2:44 PM, Lasse Boisen Andersen <
notifications@github.com> wrote:

> Could you try and post your code again? It seems it got stripped out from
> your message.
>
> It look like you're trying to configure the timekitCreateEvent with a
> custom start date. Be aware that the start: data.start from
> https://github.com/timekit-io/booking-js#timekit-create-event is merely
> an example of what is set dynamically inside Booking.js - if you want to
> override it, you'll have to set it to a timestamp string value. If in
> doubt, just exclude it (I don't think you want to override it)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/timekit-io/booking-js/issues/68#issuecomment-174481959>
> .
>



-- 


*Haris Aghadi*
Co-Founder, Meddy
e:haris@meddy.co | w:www.meddy.co
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs5wLKFbW7dKKvF1qMyF6W7fZnDC56dxFyf4SwCYx02?t=http%3A%2F%2Flinkedin.com%2Fin%2Fhaghadi&si=5978230864740352&pi=488572c9-5971-438e-c739-7e428e6a5744>

<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs5wLKFbW7dKKvF1qMyF6W7fZnDC56dxFyf4SwCYx02?t=http%3A%2F%2Ftwitter.com%2Fhaghadi&si=5978230864740352&pi=488572c9-5971-438e-c739-7e428e6a5744>
Get a signature like this:
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs5wLKFbW7dKKvF1qMyF6W7fZnDC56dxFyf4SwCYx02?t=http%3A%2F%2Fws-stats.appspot.com%2Fr%3Frdata%3DeyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8%2FdXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9&si=5978230864740352&pi=488572c9-5971-438e-c739-7e428e6a5744>
Click
here!
<http://t.sidekickopen36.com/e1t/c/5/f18dQhb0S7lC8dDMPbW2n0x6l2B9nMJW7t5XZs5wLKFbW7dKKvF1qMyF6W7fZnDC56dxFyf4SwCYx02?t=http%3A%2F%2Fws-stats.appspot.com%2Fr%3Frdata%3DeyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS8%2FdXRtX3NvdXJjZT1leHRlbnNpb24mdXRtX21lZGl1bT1lbWFpbCZ1dG1fY2FtcGFpZ249cHJvbW9fNDUiLCAiZSI6ICJwcm9tb180NV9jbGljayJ9&si=5978230864740352&pi=488572c9-5971-438e-c739-7e428e6a5744>
