### ISSUE TITLE
Timekit Filter Business hours customization?

### ISSUE THREAD

**Issue by alialkhatib** [timekit-io/booking-js#69]
Maybe this is exposed already, but the documentation leaves me with some questions and maybe someone can clarify.

Some of the people I'm working with would like to describe their business hours as something like 10am-4pm (for example). This means differing from the timezone type of parameter that `business_hours` typically accepts, but other solutions don't seem to do what I'm looking for. Maybe I'm wrong, so I'll give my understanding of how the other apparent solutions seem to work, and maybe someone can correct me :)

- `between_timestamps`: will find slots of N duration between timestamp `A` and timestamp `B`, but `A` and `B` have to be exact dates (so I can't say "Mondays-Fridays 10am-3pm"; I have to say the equivalent of "between Monday, February 1 at 10AM and Monday, February 1 at 3PM").
- `specific_time` (and `specific_day_and_time`): will find slots starting at `specific_time.start` and ending at `specific_time.end` (but my sense is this could conflict with a parameter like `length: '4 hours'`).

Am I mistaken? The ideal "power user" scenario (from my perspective) would be to allow people to say that they work from `A` to `B` and drop the timezone dependence entirely. If someone wants to moonlight from 5pm to 10pm with booking.js, it'd be great if this would let them (without having to do anything weird like change their timezone and block off everything after 10pm with placeholder events or something).

**Comment by laander** [comment]
@alialkhatib I'm not totally sure I understand your problem, but first of, the timezone flag for `business_hours` is completely optional. If you don't supply it, the calendar owner's timezone will be used (synced from Google or the one supplied on user creation).

The `specific_time` is properly what you're looking for if you want "custom" business hours. Just supply it like so: `{ "specific_time": {"start": 17, "end": 22} }` and you'll get timeslots that only fit within borders. You can also combine it with other filters, e.g. `{ "specific_day": {"day": "Monday"} }` to only get mondays or multiple to only get from Monday to Friday.

Makes sense or did I misunderstand your question?
