### ISSUE TITLE
Previous and Next buttons don't work in mobile

### ISSUE THREAD

**Issue by univers** [timekit-io/booking-js#70]
I have implemented the booking.js plugin and it is beautiful. Nice work. Works really well in PC.

I tested the implementation on mobile and I can't tap the previous and next to look at the following days.

Any ideas or remedies?

**Comment by univers** [comment]
Alright upon further review the .fc-toolbar is being overlapped by the display name.

If you make the .fc-toolbar relative and add a z-index higher it resolves the conflict which is merely a css thing and not a js event issue.

`.fc .fc-toolbar {
                                position: relative !important;
                                z-index: 40 !important;
                        }`

**Comment by laander** [comment]
@univers Thanks for reporting! I have a PR open that fixes that particular issue, see here: https://github.com/timekit-io/booking-js/pull/66

I'll get it released today :+1:

**Comment by laander** [comment]
@univers Fix has been released. Thanks again.
