### ISSUE TITLE
Override default template strings

### ISSUE THREAD

**Issue by hughstephens** [timekit-io/booking-js#74]
Hi team

Have had a dig around, but is there a way to override the default strings in main.js?

https://github.com/timekit-io/booking-js/blob/f5205f4f505bdf09249fee630dccc6876d958ba2/src/main.js#L303

For example, we've noticed that a number of users think that booking.js is "broken" when it takes 15-30 seconds to complete the 'booking' action. If we could override the default booking button (for our particular use case, where some customers are less tech savvy) to something like submitText: "Book now (allow 30 seconds)" that would make life a lot easier.

Thanks

**Comment by laander** [comment]
Hey @hughstephens , we've just released v1.7.0 with support for customizable strings in e.g. submit button and success message. Please see this section: https://github.com/timekit-io/booking-js#--localization

We've also made some improvements to the Google sync, so submitting should only take 3-6 seconds now. If you still encounter slow response times, please ping me!

**Comment by hughstephens** [comment]
Great, thanks @laander :)
