### ISSUE TITLE
prefilled and locked values aren't submitted

### ISSUE THREAD

**Issue by pleasetrythisathome** [timekit-io/booking-js#75]
When prefilling and then locking values, undefined is submitted to the submitBookingForm callback

**Comment by laander** [comment]
@pleasetrythisathome You're right, looking into this, thanks for reporting

**Comment by laander** [comment]
@pleasetrythisathome Just making sure you know that the bug was fixed in release v1.7.0 :+1:

**Comment by pleasetrythisathome** [comment]
got it thanks!
