### ISSUE TITLE
Time slot booked multiple times bug?

### ISSUE THREAD

**Issue by lawrence89** [timekit-io/booking-js#76]
I've notice that if two separate users happens to open up bookingjs calendar page at the same time, user A selects a time slot, and then user B selects the same time slot 2 minutes later, they end up both booking the same slot. Is there any way to prevent the second user from booking the same slot and give them an error message?

**Comment by laander** [comment]
@lawrence89 Good question. Currently, event creation does not take existing events into account, only the findtime availability request does. We're considering adding a flag though that checks for overlapping events and throws an error if found. 

I'll keep this issue open as a feature request until we have time to look at it.

**Comment by scottini** [comment]
+1
please consider this feature request ;)

**Comment by hughstephens** [comment]
+1. Frustrating that it doesn't do this already, as we have a few users who will leave a tab / window open for a while before booking.

**Comment by laander** [comment]
@hughstephens @scottini @lawrence89 We're working on this right now, expect a release by the beginning of next week.

**Comment by hughstephens** [comment]
Great, thanks @laander :)

**Comment by Jaamie** [comment]
Hey, just wanted to see if this was released/fixed? I'm having the same problem. :) @laander

**Comment by jacoor** [comment]
Hello @laander :-)
Can you let us know what is the state of the issue? I just managed to create an overlapping booking.

Thanks!

**Comment by bipin244** [comment]
Hello friend,
any update on this or any other way to avoid this?

**Comment by laander** [comment]
@bipin244 This has been supported and enabled by default for quite a few years now. To disable it on a per-booking basis, you can pass `settings.allow_double_bookings: true` to your API request - please see https://developers.timekit.io/reference
