### ISSUE TITLE
Did you have issues with loadFixtures()?

### ISSUE THREAD

**Issue by cameronjroe** [timekit-io/booking-js#77]
I noticed you guys used karma with jasmine-jquery, I was just wondering if you happened to run into an issue where the fixtures won't load into Chrome because of a content privacy policy or something? Also, how did you get around it?

**Comment by laander** [comment]
Hi @cameronjroe, I don't recall any issues like that, but I did have some issues with it getting it to work in the first run. You can check the source and run it locally - perhaps that will give some insights. 

Here's a quick walkthrough of what we do:

In my `karma.conf.js`, I have this:
```
files: [
  'node_modules/jquery/dist/jquery.js',
  'node_modules/jasmine-jquery/lib/jasmine-jquery.js',
  { pattern: 'test/*.spec.js',          included: true,  served: true, watched: true },
  { pattern: 'test/fixtures/**/*.html', included: false, served: true, watched: true }
]  
```

In the fixture html file, I serve the lib locally:
`<script type="text/javascript" src="/base/dist/booking.js"></script>`

And then use it specs like so:
`jasmine.getFixtures().fixturesPath = 'base/test/fixtures';`

**Comment by cameronjroe** [comment]
I see. I'm testing with a static site so unfortunately I needed to strip the script tag and just replace the document.body with the fixture instead. Also, it turns out there's a XMLHttpRequest deprecation for synchronous requests which means that fixtures don't load in latest version of Chrome. Got it work though - all good :+1:
