### ISSUE TITLE
confirm_decline flow not working

### ISSUE THREAD

**Issue by pleasetrythisathome** [timekit-io/booking-js#81]
response
{"error":"Cannot apply action 'confirm' to current state 'initialized'"}

with options

```json
timekitCreateBooking:
     {graph: "confirm_decline",
      event: {invite: true,
              my_rsvp: "needsAction"}}
```

**Comment by vistik** [comment]
Hey @pleasetrythisathome 
You need to apply the action `create` first. You can set it in the initial request like this: `action: create`. If this does not fix your problem let me know :)

- Visti

**Comment by laander** [comment]
@pleasetrythisathome Actually, if you just set `bookingGraph: 'confirm_decline'` in the root of the conf, that should handle it automatically. Settings passed to `timekitCreateBooking` is only if you want to override any of the default behaviour in that graph.

**Comment by pleasetrythisathome** [comment]
hey guys, when i do either of the above i get "TimekitBooking Error: An error with Timekit createBooking occured, context: TypeError: Cannot read property 'event_info' of undefined".

Basically i just want the default behavior of the previous version, where a gcal invite is sent to both email addresses and the event is added to both calendars.

Do you have an example config? I'm a little unclear about all of the changes with the migration

**Comment by laander** [comment]
@pleasetrythisathome Could you try again? You're doing it right, a deploy went wrong and you apparently hit the API right between migrations. Sorry about that

**Comment by laander** [comment]
@pleasetrythisathome We've tested it and we found it to be resolved, closing issue. Please re-open if you still encounter any problems
