### ISSUE TITLE
Invite confirmation

### ISSUE THREAD

**Issue by AlexandraZS** [timekit-io/booking-js#84]
Would it be possible to brand the confirmation email sent to participants? So, instead of the email containing the Timekit logo, could it contain my own logo? If not, would it be possible to remove the Timekit logo?

**Comment by laander** [comment]
Hi @AlexandraZS, the free Timekit plan included the email as it is with no customizations. Our paid plans do however include webhooks, so you could setup Mandrill or Mailgun and send out custom emails on your own.

**Comment by hughstephens** [comment]
Hi @laander are we able to disable it though (as in the email being sent)? From what I can see in the stage docs it isn't possible?

**Comment by laander** [comment]
@hughstephens You can disable the emails. The setting to pass in the config is dependent on which graph you choose (`instant` vs. `confirm_decline`). 

For `instant`, you can disable the emails like so:
```
timekitCreateBooking: {
  notify_owner_by_email: {
    enabled: false
  }
  notify_customer_by_email: {
    enabled: false
  }
}
```
For `confirm_decline`:

```
timekitCreateBooking: {
  send_confirm_decline_email_to_owner: {
    enabled: false
  },
  notify_customer_by_email: {
    enabled: false
  },
  notify_customer_declined_by_email: {
    enabled: false
  }
}
```

**Comment by alvinwoon** [comment]
Just to confirm, we have to pay $599/month to get webhook access? I suppose there's no way to modify the email template with the $99 plan?

**Comment by siruguri** [comment]
I could disable the event calendar invite, via `event: {invite: false}` inside `timekitCreateBooking` but I can't disable the notification. Adding in the following:

```
 notify_customer_declined_by_email: {
    enabled: false
 }

```

causes a 403 error that reads

```
TimekitBooking Error: An error with Timekit createBooking occured, context: [object Object]
logError @ booking.min.js:42
(anonymous) @ booking.min.js:1
```
