### ISSUE TITLE
Busted migration throwing event_info undefined

### ISSUE THREAD

**Issue by hughstephens** [timekit-io/booking-js#85]
Hi guys

Seems the migration you've made that is throwing this

`TimekitBooking Deprecated: config key "timekitCreateEvent" has been replaced, use "timekitCreateBooking" and see docs`

isn't backwards compatible. Even after I tried updating to 

```
timekitCreateBooking: {
                                graph: 'instant',
                                action: 'confirm',
                                event: {
                                    what: 'XXX activation / training for <%= XXX.companyName %>',
                                    where: 'Your computer - we will call on the number you gave us.',
                                    description: 'Please make sure you\'ve watched the training videos before our session. If you need to cancel or rebook your activation, call us on YYY or email ZZZ. This install is for <%= BBB %>.'
                                }
                            },
```

I'm still getting 

`TimekitBooking Error: An error with Timekit createBooking occured, context: TypeError: Cannot read property 'event_info' of undefined`

Thanks

**Comment by hughstephens** [comment]
Update: worked out it's because you've changed the response via the API on `createBookingSuccessful` to have an 'event' object. So sorry, not about createBooking object.

`createEventSuccessful` just throws the above error, but because you're calling booking first then we can still detect it and redirect the page. End-user still sees the red "x" briefly (and it logs the error) before we redirect though… FWIW our callback is

```
callbacks: {
                                createBookingSuccessful: function (response) {
                                    console.log(response);
                                    var bookedDate = encodeURIComponent(response.data.event.start);
                                    var desc = encodeURIComponent(response.data.event.description);
                                    window.location.href = '<%= baseUrl %>' + '/company/<%= company.key %>/bookingcomplete?dateBookedFor=' + bookedDate + "&description=" + desc;
                                }
                            }
```

**Comment by laander** [comment]
@hughstephens Thanks for reporting. Actually, you were right in the first take, as we had some really weird intermittent problem where `attributes.event_info` wasn't returned successfully. After a redeploy, it's back to normal - we'll keep an eye on this for the future.

Could you check `createEventSuccessful` callback again? It should contain all the event details that we're posted, but if you want the full booking object (with customer info too), please use `createBookingSuccessful`

**Comment by hughstephens** [comment]
Hi @laander getting this again – we had to change the code above to match what I presume is a new response (now `response.config.data.event.start` – data is in config object while response.data is now just contextual info). Same problem - throws 'event_info' undefined. 

Has something changed on your side API wise?
