### ISSUE TITLE
Calendar not updating availability with times from other calendars

### ISSUE THREAD

**Issue by phangjeff** [timekit-io/booking-js#87]
My calendar is allowing for the booking of times that are currently occupied by another included calendar.   
Is this an issue on my end? 

Please contact, willing to do a paid service if there is an option for some sort of support

**Comment by laander** [comment]
@phangjeff The widget should only show timeslots where there are no existing events in your calendars. If you're using our API directly, you should know that `[POST] /events` are **not ** checking for existing events. Also, after a booking has been made, another visitor with the widget open could potentially double-book the same timeslot (until they refresh the widget).

Does the above help clarify the issue? If not, could you elaborate on the problem?

**Comment by scottini** [comment]
> Also, after a booking has been made, another visitor with the widget open could potentially double-book the same timeslot (until they refresh the widget).
There is a way to avoid this behavior? It happens only with API direct call or always?

**Comment by laander** [comment]
@scottini We're considering adding a check upon event creation that makes sure an event is not present in the same timeframe, but is hasn't been developed yet. 

There is another issue on this, #76 - throw a comment in there and we'll consider it for the next sprint

**Comment by scottini** [comment]
done!

**Comment by bipin244** [comment]
Any Updates?

**Comment by laander** [comment]
I've updated this thread with a comment: https://github.com/timekit-io/booking-js/issues/76
