### ISSUE TITLE
Booking schedule missing in email confirmation

### ISSUE THREAD

**Issue by alvinwoon** [timekit-io/booking-js#88]
The date is there (although formatting can be improved) but there's no time slot within the confirmation email. 

![image](https://cloud.githubusercontent.com/assets/1026383/13520160/e497e76e-e218-11e5-9e5d-2ea333b429e0.png)

**Comment by laander** [comment]
@alvinwoon Looks like some formatting has gone bonkers.

Are you supplying a custom `Timekit-OutputTimestampFormat` or `localization.emailTimeFormat`? If so, could you share it?

By default, it should output the following:
`Y-m-d ha (P e)`

**Comment by alvinwoon** [comment]
@laander nope. This is the full config:

`window.timekitBookingConfig = {
      name: 'Coaching Session',
	  email: 'xxx@gmail.com',
      apiToken: 'xxx',
      calendar: 'xxx',
	  fullCalendar: {
        lang: 'en' // Specify the FullCalendar language shortname
      },
      timekitFindTime: {
     	length: '1 hour',
        future: '6 months',
        filters: {
          or: [
            { specific_day_and_time: {"day": "Tuesday", "start": 9, "end": 14}},
            { specific_day_and_time: {"day": "Wednesday", "start": 9, "end": 14}},
          ]
        }
      },
      showCredits :false,
      goToFirstEvent:true,
      bookingGraph: 'confirm_decline',
      ignore_all_day_events: true,
      bookingFields : {
        name: {
          placeholder: 'Name',
          prefilled: false
        },
        email: {
          placeholder: 'Email',
          prefilled: false
        },
        comment: {
          enabled: true,
          placeholder: 'Comments',
          prefilled: false,
          required: false
        },
        phone: {
          enabled: true,
          placeholder: 'Phone number',
          prefilled: false,
          required: false
        }
      },
      localization: {
        timeDateFormat: true
      }
    }`

**Comment by alvinwoon** [comment]
Problem seems to be fixed now :+1:

**Comment by scottini** [comment]
About date formatting... How to interpret these dates? There is a way to improve readability or otherwise change date formatting on confirmation masseges?

**Comment by vistik** [comment]
Hi @scottini 

You can see supported date formats here: https://developers.timekit.io/docs/types--formatting

**Comment by scottini** [comment]
Hi @vistik 
if you take a look at alvinwoon's picture, the dates don't seem to me as written in ordinary ISO 8601 format...
How do you interpret the "000000308" part? And why the start date and the end date are perfectly equal?
And most important: how can I pass formatting parameters for the auto-generated confirmation request message?

TX!

**Comment by alvinwoon** [comment]
@scottini i think that was a bug, not the default. Without setting any format, it should display nicely. Like this:
![image](https://cloud.githubusercontent.com/assets/1026383/13740361/528fb98c-ea0b-11e5-935c-820f9541458d.png)

**Comment by scottini** [comment]
Same here...

![schermata 2016-03-14 alle 10 40 28](https://cloud.githubusercontent.com/assets/2796426/13740607/04d98c92-e9d2-11e5-894c-aaddf2ccd594.jpg)


@laander : it's better to open another bug ticket?

**Comment by alvinwoon** [comment]
Interesting!. I will reopen it for you then. Probably be helpful if you paste the entire embed codes.

**Comment by laander** [comment]
@scottini @alvinwoon In the code example, you've set:
```
localization: {
  timeDateFormat: true
}
```
This is not correct (sorry if the docs are unclear on that). The `timeDateFormat` only takes the following three values:
- `12h-mdy-sun`
- `24h-dmy-mon`
- `false` 

Internally, it's used to "preset" localization settings across the widget. You can see the source here: https://github.com/timekit-io/booking-js/blob/master/src/defaults.js

If you set it to `false`, not presets will be set and you'll have to set all the `fullCalendar` settings manually. In most use cases, just use one of the two presets that fits best.

**Comment by alvinwoon** [comment]
yep. after i remove localization everything is alright.

**Comment by scottini** [comment]
... not for me!
Here the printscreen:
![schermata 2016-03-14 alle 11 02 32 copia](https://cloud.githubusercontent.com/assets/2796426/13741107/a927bf56-e9d4-11e5-9625-18b522be5223.png)

How can I embed my code? If I insert it between 2 small apex \`\` from the top menu, the preview result is a mess...

**Comment by vistik** [comment]
I think you should use 3 of these ` to make it able to handle multiple lines

**Comment by scottini** [comment]
> I think you should use 3 of these ` to make it able to handle multiple lines

I've tried with 3 \` in front and also inserting the code between two series of 3 \`, but it shows always nothing...

**Comment by vistik** [comment]
could you try to make a gist then?

**Comment by scottini** [comment]
Yes! I'm an absolute beginner, until two minutes ago I did not know what a gist was...

https://gist.github.com/scottini/049a9c6f904944f6cd6c

**Comment by vistik** [comment]
@scottini  You have set
```
localization: {
  timeDateFormat: true
}
```
This is not correct (sorry if the docs are unclear on that). The `timeDateFormat` only takes the following three values:
- `12h-mdy-sun`
- `24h-dmy-mon`
- `false`

**Comment by scottini** [comment]
Sorry, I've badly interpreted laander's suggestion. Before his post, my timeDateFormat was false.
Now I've set it to 24h-dmy-mon, and everything works.
Thanks!

**Comment by vistik** [comment]
perfect :)
