### ISSUE TITLE
Cannot have a one-hour lunch break when 'length" is set to more than one hour

### ISSUE THREAD

**Issue by mikegcox** [timekit-io/booking-js#92]
If you look at the code below, you can see I want three hour appointments and I want a one hour lunch break.  What I end up with is my first appointment starting at 9AM and ending at 12PM (perfect) but my second appointment does not start until 3PM and goes to 6PM.  I want the appointment to start at 1PM and end at 4PM.  

```
timekitFindTime: {
        filters: {
          and: [
            {
              business_hours: {"timezone": "America/New_York"}
            },
            {
              exclude_weekend: { }
            }
          ],
          or: [
            {
              specific_time: {
                start: '00',
                end: '12'
              }
            },
            {
              specific_time: {
                start: '13',
                end: '24'
              }
            }
          ]
        },
        length: '3 hours'
      }
```

**Comment by laander** [comment]
Hi @mikegcox we're aware of a bug with the availability engine that sometimes leaves some unintended free spots when using back-to-back filters. My best suggestion meanwhile is to either increase the availability frame or decrease the timeslot duration to allow more "breathing room".

**Comment by mikegcox** [comment]
Okay, thanks. That is indeed what I did in the end. Thanks for the great script.
