### ISSUE TITLE
Event added to wrong Calendar, and booking.js does not refresh when event deleted

### ISSUE THREAD

**Issue by sbiefeni** [timekit-io/booking-js#94]
I created a calendar just for my booking.js script.. however when adding events they get added to my default calendar instead. 
When I create or delete events on my google calendar, the booking.js widget is not updated.. until I book a new time in the widget, then it seems to refresh.. how can we force the calendar to refresh?

**Comment by laander** [comment]
Hi @sbiefeni , we sync events from your Google calendar every 2 hours, so it's not totally realtime. We're working on improving this continually though with instant sync coming within the next months!
